[build]
  command = "pnpm install && pnpm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--version"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  
NEXT_PUBLIC_FIREBASE_API_KEY=AIzaSyDo8-El3Lihj0I5eM73d-BthbAVLOavcP0
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=booknest-1a268.firebaseapp.com
NEXT_PUBLIC_FIREBASE_PROJECT_ID=booknest-1a268
NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=booknest-1a268.firebasestorage.app
NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=1001818574183
NEXT_PUBLIC_FIREBASE_APP_ID=1:1001818574183:web:d8e15ce7516b1c4c3bb3c2